# model params
backbone:

image_size: 112
embedding_size: 512



# hyper params
optimizer: 'ADAM'    # ADADELTA, ADAGRAD, ADAM, ADAMAX, FTRL, NADAM, RMSPROP, SGD
learning_rate: 0.01

loss_type: 'logit'   # logit or triplet
logits_scale: 64.0
logits_margin1: 1.0   # m1: sphereface should >= 1
logits_margin2: 0.2   # m2: cosineface should >= 0
logits_margin3: 0.3   # m3: arcface    should >= 0

center_loss_factor: 0.0  # center loss
center_alpha: 0.9   # center update rate

alpha: 0.2     # triplet margin

# run params

batch_size: 16
epoch_num: 100

valid_num: 256          # half pos and half neg
valid_batch_size: 16
thresh: 0.2
below_fpr: 0.001        # fpr should below this
# paths

train_dir: '~/data/insightface/recognition/train'
valid_dir: '~/data/insightface/recognition/val'
test_dir:
ckpt_dir: '~/models/insightface/recognition'
summary_dir: '~/logs/insightface/recognition/summary'